### ISSUE TITLE
Does not generate any note

### ISSUE THREAD

**Issue by javiavid** [Canna71/obsidian-readlater#1]
Hello, I have tried with the bookmarklet, with the clipboard option and with pocket, but no note has been generated with any of the options.

I installed it with BRAT, activated it and set the download folder and Pocket.
Is it necessary to do something else?

SYSTEM INFO:
	Obsidian version: v1.1.3
	Installer version: v0.15.6
	Operating system: Windows 10 Pro 10.0.22621
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: none
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 17
	Plugins enabled: 2
		1: Read later v0.8.1
		2: Obsidian42 - BRAT v0.6.36

**Comment by jjmaldonis** [comment]
I just ran into the same problem and fixed it by adding a new folder called `Read Later` at the top level of my vault. All new notes seem to be saved to this folder.

@Canna71 it might be worth a `new Notice("Please create a top-level folder called Read Later", 10000)` if this happens, or to create the folder automatically.

But this fixed it for me!

Thanks for this plugin, I've been wanting something like it for a long time. The sync feature is cool too.

**Comment by Canna71** [comment]
I am very sorry, I will fix this as soon as possible. In the meantime I added a note to the README

**Comment by javiavid** [comment]
Thanks, creating that folder works correctly.

**Comment by Canna71** [comment]
OK, this should be fixed in 0.8.2.
Folder settings is now exposed in the settings. If left empty should default to the vault's root.
